server:
  port: 8888

info:
  description: Spring Cloud Config Server
  
spring:
  application:
    name: spring-boot-gitprofiles-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codependent/spring-boot-gitprofiles-config.git
              
          